apiVersion: v1
kind: Service
metadata:
  name: collector-metrics
  namespace: iiot
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: iiot-edge-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: collector
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
