apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iiot

labels:
  - pairs:
      app.kubernetes.io/part-of: iiot-edge-platform
      managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - mosquitto-configmap.yaml
  - mosquitto-deployment.yaml
  - mosquitto-service.yaml
  - collector-deployment.yaml
  - collector-service.yaml
  - mqtt-bridge-deployment.yaml
  - mqtt-bridge-service.yaml
  - ingestor-deployment.yaml
  - ingestor-service.yaml
