apiVersion: v1
kind: Service
metadata:
  name: mqtt-bridge-metrics
  namespace: iiot
  labels:
    app.kubernetes.io/name: mqtt-bridge
    app.kubernetes.io/part-of: iiot-edge-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt-bridge
  ports:
    - name: metrics
      port: 9092
      targetPort: 9092
      protocol: TCP
